### ISSUE TITLE
Implement surge.sh for testing

### ISSUE THREAD

**Issue by thekaveman** [CityofSantaMonica/beta-smgov#1]
See allejo/travis-to-surge-test#1

**Comment by thekaveman** [comment]
@allejo this is just an FYI for you, not something we need to figure out right now exactly... but the current thinking is we will want to host this site on Azure Web Apps, and have much of the same pipeline as we have for [analytics.smgov.net](https://github.com/CityofSantaMonica/analytics.smgov.net)

**Comment by allejo** [comment]
Sure, is it something complicated (relatively) like pulling Python deps going to be necessary or just building Jekyll?

btw, feel free to rebase your branches with master to pull in the Travis changes for future PRs

**Comment by thekaveman** [comment]
Hopefully nothing more complicated than building the Jekyll site and deploying. That's the plan for now anyway. 

And thanks, good idea about rebasing. @sevilturner and I will definitely look to do that. Do we get a unique surge.sh site per branch/PR?

**Comment by allejo** [comment]
Yup. Each surge.sh site has the PR number in the URL
